[meta]
id = "clear_sky"
display_name = "Clear Sky"

[soft_constraints]
prefers_locations = [
    "park",
    "street",
    "beach",
    "mountain",
    "balcony",
    "rooftop",
]
prefers_actions = [
    "exercising",
]
prefers_lighting_sources = [
    "sunlight",
    "natural lighting",
    "blue hour",
]
