[meta]
id = "cloudy"
display_name = "Cloudy"

[soft_constraints]
prefers_locations = [
    "street",
    "park",
    "cafe",
    "beach",
    "mountain",
]
prefers_actions = [
    "reading",
]
prefers_lighting_sources = [
    "soft lighting",
    "diffused lighting",
    "overcast lighting",
]
