[meta]
id = "fog"
display_name = "Fog"

[soft_constraints]
prefers_locations = [
    "forest",
    "mountain",
    "lake",
    "street",
    "park",
]
prefers_actions = []
prefers_lighting_sources = [
    "misty lighting",
    "foggy lighting",
    "ethereal lighting",
    "dreamy lighting",
    "gloomy lighting",
]
