[meta]
id = "beach"
display_name = "Beach"
type = "outdoor_aquatic"

[soft_constraints]
prefers_actions = [
    "cooking",
]
prefers_lighting_sources = [
    "sunlight",
    "bright_sunlight",
    "golden_hour",
    "sunset",
    "sunrise",
]
prefers_lighting_quality = [
    "natural_lighting",
    "hard_lighting",
    "golden_hour",
    "warm_lighting",
]
prefers_props = [
    "beach_towel",
    "beach_umbrella",
    "beach_ball",
    "sunglasses",
    "sunscreen",
    "flip_flops",
    "surfboard",
]
prefers_lighting = [
    "sunlight",
]
