[meta]
id = "bedroom"
display_name = "Bedroom"
type = "indoor_private"

[soft_constraints]
preferred_outfit_categories = [
    "black pajamas",
    "blue pajamas",
    "button-up pajamas",
    "cotton pajamas",
    "cozy pajamas",
    "cute pajamas",
    "fitted pajamas",
    "flannel pajamas",
    "floral pajamas",
    "frilly pajamas",
    "long sleeve pajamas",
    "nightgown",
    "oversized pajamas",
    "pajama set",
    "pajama shorts",
    "pajama top and pants",
    "pajamas",
    "pastel pajamas",
    "pink pajamas",
    "plaid pajamas",
    "polka dot pajamas",
    "satin pajamas",
    "short sleeve pajamas",
    "silk pajamas",
    "sleep shirt",
    "sleep shorts",
    "striped pajamas",
    "white pajamas",
]
avoid_outfit_categories = [
    "athleisure",
    "casual home outfit",
    "casual home wear",
    "casual loungewear",
    "comfy outfit",
    "cozy home clothes",
    "hoodie and shorts",
    "joggers and t-shirt",
    "knit lounge set",
    "leggings and oversized shirt",
    "long sleeve shirt and lounge pants",
    "loungewear",
    "oversized t-shirt and shorts",
    "relaxed fit outfit",
    "soft cotton outfit",
    "sweatpants and hoodie",
    "sweatshirt and shorts",
    "tank top and sweatpants",
    "track suit",
    "yoga pants and crop top",
]
prefers_actions = [
    "adjusting clothes",
    "adjusting hair",
    "daydreaming",
    "reading",
    "stretching",
    "thinking",
    "undressing",
]
avoid_actions = []
prefers_props = [
    "bunny plushie",
    "cat plushie",
    "holding teddy bear",
    "hugging teddy bear",
    "plush teddy bear",
    "plush toy",
    "sleeping with teddy bear",
    "stuffed animal",
    "teddy bear",
]
avoid_props = []
prefers_lighting_sources = []
avoid_lighting_sources = []
prefers_weather = []
avoid_weather = []

[hard_constraints]
allowed_outfit_categories = [
    "adhesive bra",
    "backless bra",
    "balconette bra",
    "bandeau bra",
    "beige bra",
    "beige panties",
    "bikini panties",
    "black boyshorts",
    "black bra",
    "black bralette",
    "black briefs",
    "black pajamas",
    "black panties",
    "black sports bra",
    "blue bra",
    "blue pajamas",
    "blue panties",
    "bow panties",
    "boyshorts",
    "bra with bow",
    "bra with lace trim",
    "bra with ribbon",
    "bra with ruffles",
    "bralette",
    "briefs",
    "bustier",
    "button-up pajamas",
    "casual home outfit",
    "casual home wear",
    "casual loungewear",
    "checkered bra",
    "checkered panties",
    "cheeky panties",
    "comfy outfit",
    "control top panties",
    "convertible bra",
    "corset bra",
    "cotton bra",
    "cotton pajamas",
    "cotton panties",
    "cozy home clothes",
    "cozy pajamas",
    "crotchless panties",
    "cute pajamas",
    "demi bra",
    "embroidered bra",
    "embroidered panties",
    "fitted pajamas",
    "flannel pajamas",
    "floral bra",
    "floral pajamas",
    "floral panties",
    "frilled panties",
    "frilly pajamas",
    "front closure bra",
    "g-string",
    "high-cut panties",
    "high-waisted panties",
    "hipsters",
    "lace bra",
    "lace bralette",
    "lace panties",
    "lace trim panties",
    "long sleeve pajamas",
    "longline bra",
    "loungewear",
    "low-rise panties",
    "maximizer bra",
    "mesh bra",
    "mesh panties",
    "minimizer bra",
    "nightgown",
    "nursing bra",
    "open crotch panties",
    "oversized pajamas",
    "padded bra",
    "pajama set",
    "pajama shorts",
    "pajama top and pants",
    "pajamas",
    "pastel pajamas",
    "pink bra",
    "pink pajamas",
    "pink panties",
    "plaid pajamas",
    "plaid panties",
    "plunge bra",
    "polka dot bra",
    "polka dot pajamas",
    "polka dot panties",
    "push-up bra",
    "racerback sports bra",
    "red bra",
    "red panties",
    "ribbon panties",
    "ruffled panties",
    "satin bra",
    "satin pajamas",
    "satin panties",
    "seamless panties",
    "shaping panties",
    "sheer bra",
    "sheer panties",
    "short sleeve pajamas",
    "side-tie panties",
    "silk bra",
    "silk pajamas",
    "silk panties",
    "sleep shirt",
    "sleep shorts",
    "sports bra",
    "strappy bra",
    "string panties",
    "striped bra",
    "striped pajamas",
    "striped panties",
    "t-back panties",
    "t-shirt bra",
    "thong",
    "tube bra",
    "underwire bra",
    "v-string panties",
    "white boyshorts",
    "white bra",
    "white bralette",
    "white briefs",
    "white pajamas",
    "white panties",
    "white sports bra",
    "wireless bra",
]
excludes_outfit_categories = [
    "a-line dress",
    "a-line skirt",
    "ankle boots",
    "asymmetrical dress",
    "asymmetrical skirt",
    "athleisure",
    "athletic shoes",
    "athletic shorts",
    "backless dress",
    "baggy jeans",
    "ball gown",
    "ballet flats",
    "basketball shorts",
    "beige chinos",
    "beige dress",
    "biker shorts",
    "black ankle boots",
    "black cargo pants",
    "black combat boots",
    "black denim shorts",
    "black dress",
    "black dress pants",
    "black jeans",
    "black knee-high boots",
    "black leather pants",
    "black leggings",
    "black loafers",
    "black mary janes",
    "black sneakers",
    "black sweatpants",
    "black thigh-high boots",
    "block heels",
    "blue denim jeans",
    "blue denim shorts",
    "blue dress",
    "board shorts",
    "boat shoes",
    "bodycon dress",
    "bootcut jeans",
    "booty shorts",
    "brogues",
    "brown ankle boots",
    "brown knee-high boots",
    "brown loafers",
    "button-front skirt",
    "canvas sneakers",
    "cargo pants",
    "cargo shorts",
    "cargo skirt",
    "checkered dress",
    "checkered pants",
    "checkered shorts",
    "checkered skirt",
    "chelsea boots",
    "chiffon dress",
    "chinos",
    "chukka boots",
    "circle skirt",
    "cocktail dress",
    "cold shoulder dress",
    "combat boots",
    "corduroy dress",
    "corduroy pants",
    "corduroy skirt",
    "cowboy boots",
    "culottes",
    "dark wash jeans",
    "denim dress",
    "denim shorts",
    "denim skirt",
    "derby shoes",
    "distressed denim shorts",
    "distressed jeans",
    "dress pants",
    "elastic waist skirt",
    "empire waist dress",
    "espadrilles",
    "evening gown",
    "faux leather pants",
    "fit and flare dress",
    "fitted dress",
    "flared jeans",
    "flat boots",
    "floral dress",
    "floral skirt",
    "floral sundress",
    "flowy dress",
    "frilled dress",
    "go-go boots",
    "green dress",
    "grey sweatpants",
    "gym shorts",
    "halter dress",
    "heeled boots",
    "high-low dress",
    "high-top sneakers",
    "high-waisted jeans",
    "high-waisted shorts",
    "high-waisted skirt",
    "hiking boots",
    "hoodie and shorts",
    "hot pants",
    "joggers",
    "joggers and t-shirt",
    "khaki pants",
    "khaki shorts",
    "kitten heels",
    "knee-high boots",
    "knit dress",
    "knit lounge set",
    "lace dress",
    "lace skirt",
    "lace-up boots",
    "leather knee-high boots",
    "leather pants",
    "leather shorts",
    "leather skirt",
    "leather sneakers",
    "leather thigh-high boots",
    "leggings",
    "leggings and oversized shirt",
    "light wash jeans",
    "linen shorts",
    "little black dress",
    "loafers",
    "long sleeve shirt and lounge pants",
    "loose dress",
    "low-rise jeans",
    "low-waisted skirt",
    "mary janes",
    "maxi dress",
    "maxi skirt",
    "midi dress",
    "midi skirt",
    "mini dress",
    "miniskirt",
    "moccasins",
    "navy chinos",
    "off-shoulder dress",
    "olive cargo pants",
    "one-shoulder dress",
    "over-the-knee boots",
    "overall pants",
    "overall shorts",
    "overall skirt",
    "oversized t-shirt and shorts",
    "oxford shoes",
    "paperbag shorts",
    "party dress",
    "patent leather mary janes",
    "pencil skirt",
    "penny loafers",
    "pink dress",
    "plaid dress",
    "plaid pants",
    "plaid shorts",
    "plaid skirt",
    "platform boots",
    "platform combat boots",
    "platform shoes",
    "pleated pants",
    "pleated shorts",
    "pleated skirt",
    "pointed flats",
    "polka dot dress",
    "princess dress",
    "prom dress",
    "pumps",
    "purple dress",
    "rain boots",
    "red dress",
    "relaxed fit outfit",
    "riding boots",
    "ripped jeans",
    "rubber boots",
    "ruffled dress",
    "ruffled skirt",
    "running shoes",
    "running shorts",
    "satin dress",
    "satin skirt",
    "school shoes",
    "school skirt",
    "sheath dress",
    "shift dress",
    "shirt dress",
    "short shorts",
    "side slit skirt",
    "silk dress",
    "skater skirt",
    "skinny jeans",
    "skirt with slit",
    "skort",
    "slip-on shoes",
    "slit dress",
    "snow boots",
    "soft cotton outfit",
    "stiletto heels",
    "straight-leg jeans",
    "strapless dress",
    "strappy flats",
    "striped dress",
    "suede knee-high boots",
    "summer dress",
    "sundress",
    "suspenders skirt",
    "sweat shorts",
    "sweater dress",
    "sweatpants",
    "sweatpants and hoodie",
    "sweatshirt and shorts",
    "swim trunks",
    "t-shirt dress",
    "tailored pants",
    "tank top and sweatpants",
    "tennis shoes",
    "tennis skirt",
    "thigh-high boots",
    "tiered dress",
    "tiered skirt",
    "tight dress",
    "track pants",
    "track suit",
    "tulle dress",
    "tulle skirt",
    "tutu skirt",
    "utility skirt",
    "uwabaki",
    "velvet dress",
    "vinyl pants",
    "wedding dress",
    "wedge boots",
    "wedge shoes",
    "western boots",
    "white dress",
    "white jeans",
    "white sneakers",
    "white sundress",
    "wide-leg jeans",
    "wrap dress",
    "wrap skirt",
    "yellow dress",
    "yellow rain boots",
    "yoga pants",
    "yoga pants and crop top",
    "zip-up boots",
]
allowed_actions = [
    "adjusting clothes",
    "adjusting hair",
    "brushing hair",
    "buttoning shirt",
    "holding hands",
    "holding object",
    "holding phone",
    "hugging",
    "kissing",
    "leaning on",
    "looking at object",
    "opening window",
    "reading",
    "relaxing",
    "thinking",
    "touching",
    "undressing",
    "waking up",
]
excludes_actions = [
    "baking",
    "bathing",
    "brushing teeth",
    "catching",
    "cleaning",
    "climbing",
    "cooking",
    "coughing",
    "crawling",
    "dancing",
    "diving",
    "dodging",
    "doing laundry",
    "doing yoga",
    "drawing",
    "drinking",
    "dusting",
    "eating",
    "exercising",
    "falling",
    "fighting",
    "floating",
    "gardening",
    "holding umbrella",
    "holding weapon",
    "ice skating",
    "ironing",
    "jogging",
    "jumping",
    "kicking",
    "knitting",
    "leaping",
    "martial arts pose",
    "mopping",
    "painting",
    "playing basketball",
    "playing guitar",
    "playing instrument",
    "playing piano",
    "playing soccer",
    "playing sports",
    "playing tennis",
    "playing violin",
    "punching",
    "reading",
    "relaxing",
    "resting",
    "riding a bicycle",
    "roller skating",
    "running",
    "sewing",
    "shopping",
    "shouting",
    "showering",
    "singing",
    "skateboarding",
    "skiing",
    "skipping",
    "sleeping",
    "smiling",
    "snowboarding",
    "spinning",
    "sprinting",
    "studying",
    "surfing",
    "sweeping",
    "swimming",
    "taking off jacket",
    "throwing",
    "tripping",
    "tying ribbon",
    "tying shoes",
    "washing face",
    "washing hair",
    "washing hands",
    "writing",
    "yawning",
]
required_props = [
    "alarm clock",
    "art_book",
    "bed",
    "book",
    "bunny plushie",
    "cat plushie",
    "fantasy_book",
    "holding teddy bear",
    "hugging teddy bear",
    "magazine",
    "manga",
    "notebook",
    "novel",
    "plush teddy bear",
    "plush toy",
    "sleeping with teddy bear",
    "stuffed animal",
    "teddy bear",
]
required_props_pool = []
required_props_count = 0
excludes_props = [
    "acorn",
    "apple",
    "apron",
    "armoire",
    "arrow",
    "assault rifle",
    "autumn leaves",
    "axe",
    "backpack",
    "baking_sheet",
    "ballpoint_pen",
    "bamboo",
    "banana",
    "bandage",
    "bar stool",
    "battleaxe",
    "bazooka",
    "beer mug",
    "bento",
    "binder",
    "binoculars",
    "blaster",
    "blender",
    "bomb",
    "boomerang",
    "bottle_opener",
    "boulder",
    "bow",
    "branch",
    "brass knuckles",
    "bread",
    "bread_knife",
    "broadsword",
    "broom",
    "bubble tea",
    "bucket",
    "buckler",
    "buffet",
    "burger",
    "bush",
    "cactus",
    "cake_pan",
    "calculator",
    "camera",
    "can_opener",
    "candle",
    "candy",
    "cannon",
    "canvas",
    "chain",
    "chef_apron",
    "chef_knife",
    "cherry blossom tree",
    "cherry blossoms",
    "chips",
    "chocolate",
    "chopsticks",
    "clipboard",
    "club",
    "cocktail",
    "coffee cup",
    "colander",
    "colored_pencils",
    "compass",
    "composition_book",
    "cookie",
    "coral",
    "crayons",
    "crepe",
    "croissant",
    "crossbow",
    "curtains",
    "cutting_board",
    "dagger",
    "daisy",
    "dango",
    "desk_organizer",
    "dew drop",
    "dining chair",
    "dining table",
    "donut",
    "driftwood",
    "drill",
    "dutch_oven",
    "easel",
    "energy sword",
    "eraser",
    "fallen leaves",
    "fern",
    "flashlight",
    "floating petals",
    "flower",
    "flower petals",
    "folder",
    "food_processor",
    "fork",
    "fountain_pen",
    "fruit",
    "frying_pan",
    "gauntlet",
    "gel_pen",
    "glass",
    "globe",
    "glue",
    "glue_stick",
    "graph_paper",
    "grass",
    "grater",
    "grenade",
    "gun",
    "halberd",
    "hammer",
    "hatchet",
    "headphones",
    "highlighter",
    "holographic weapon",
    "hose",
    "ice cream",
    "ivy",
    "jelly",
    "juice box",
    "katana",
    "key",
    "kitchen_timer",
    "knife",
    "knitting needles",
    "kunai",
    "kusarigama",
    "ladder",
    "ladle",
    "lake",
    "lance",
    "lantern",
    "laptop",
    "laser gun",
    "leaves",
    "lighter",
    "lightsaber",
    "lily",
    "lily pad",
    "lock",
    "log",
    "lollipop",
    "longbow",
    "longsword",
    "loose_leaf_paper",
    "lotus",
    "lunch_box",
    "lunchbox",
    "macaron",
    "mace",
    "machine gun",
    "magic wand",
    "magical weapon",
    "magnifying glass",
    "map",
    "maple leaf",
    "maple tree",
    "marker",
    "matches",
    "measuring tape",
    "measuring_cup",
    "measuring_spoons",
    "mechanical_pencil",
    "megaphone",
    "melonpan",
    "microphone",
    "microscope",
    "milkshake",
    "mixing_bowl",
    "mop",
    "moss",
    "muffin_tin",
    "mug",
    "mushroom",
    "needle",
    "notebook",
    "nunchaku",
    "ocean wave",
    "office chair",
    "office desk",
    "onigiri",
    "oven_mitt",
    "paintbrush",
    "palette",
    "pancake",
    "paper_clip",
    "parfait",
    "pastry",
    "pebble",
    "peeler",
    "pen",
    "pencil",
    "pencil_case",
    "pencil_holder",
    "petals",
    "picnic basket",
    "pine tree",
    "pinecone",
    "pistol",
    "pizza",
    "pliers",
    "pocky",
    "pond",
    "popsicle",
    "post_it_notes",
    "pot",
    "pot_holder",
    "pressure_cooker",
    "protractor",
    "pudding",
    "puddle",
    "quiver",
    "rake",
    "ramen",
    "rapier",
    "ray gun",
    "recipe_book",
    "reeds",
    "revolver",
    "rice_cooker",
    "rifle",
    "river",
    "rock",
    "rocket launcher",
    "roller",
    "rolling_pin",
    "rope",
    "rose",
    "ruler",
    "sake cup",
    "salad",
    "sand",
    "sandwich",
    "saucepan",
    "saw",
    "scalpel",
    "scepter",
    "school_bag",
    "scientific_calculator",
    "scimitar",
    "scissors",
    "screwdriver",
    "scythe",
    "seaweed",
    "senbon",
    "sewing machine",
    "shell",
    "shield",
    "shortsword",
    "shotgun",
    "shovel",
    "shuriken",
    "sickle",
    "sketchbook",
    "skillet",
    "slice of cake",
    "smartphone",
    "sniper rifle",
    "soda can",
    "soup",
    "spatula",
    "spear",
    "spiral_notebook",
    "sponge",
    "spoon",
    "staff",
    "stand_mixer",
    "stapler",
    "starfish",
    "steamer",
    "stethoscope",
    "sticky_notes",
    "strainer",
    "straw",
    "strawberry",
    "stream",
    "string",
    "sundae",
    "sunflower",
    "sushi",
    "sword",
    "syringe",
    "tablet",
    "taiyaki",
    "takoyaki",
    "tall grass",
    "tape",
    "teacup",
    "teapot",
    "telescope",
    "textbook",
    "thermos",
    "thread",
    "throwing knives",
    "toaster",
    "tongs",
    "toolbox",
    "towel",
    "tree",
    "tree stump",
    "trident",
    "tripod",
    "tulip",
    "tweezers",
    "umbrella stand",
    "vine",
    "waffle",
    "warhammer",
    "washi_tape",
    "water bottle",
    "water drop",
    "water_bottle",
    "waterfall",
    "watering can",
    "wheelbarrow",
    "whip",
    "whisk",
    "willow tree",
    "wine glass",
    "wire",
    "wok",
    "wooden_spoon",
    "wrench",
    "yarn",
]
excludes_lighting_sources = []
excludes_weather = []
