[meta]
id = "street"
display_name = "City Street"
type = "outdoor_urban"

[soft_constraints]
prefers_actions = [
    "walking",
]
prefers_lighting_sources = [
    "sunlight",
    "streetlight",
    "neon_light",
    "shop_lights",
    "golden_hour",
    "blue_hour",
]
prefers_lighting_quality = [
    "natural_lighting",
    "urban_lighting",
    "neon_lighting",
    "cinematic_lighting",
]
prefers_props = [
    "coffee cup",
    "shopping_bag",
    "smartphone",
    "umbrella",
    "backpack",
    "camera",
]
