[meta]
id = "pov"
display_name = "Pov"

[soft_constraints]
prefers_locations = [
    "bedroom",
    "bathroom",
    "cafe",
    "kitchen",
    "train interior",
]
prefers_actions = [
    "reading",
    "drinking",
    "eating",
    "using smartphone",
    "holding object",
]
