[meta]
id = "photography"
display_name = "Photography"

[hard_constraints]
allowed_locations = []
excludes_locations = [
    "bathroom",
    "kitchen",
    "bedroom",
    "library",
    "gym",
    "classroom",
]
required_props = []
required_props_pool = []
required_props_count = 0
excludes_props = []
excludes_actions = []

[soft_constraints]
prefers_locations = []
prefers_poses = []
prefers_props = [
    "camera",
    "instant camera",
]
prefers_expressions = []
excluded_locations = []
avoid_locations = []
avoid_props = []
avoid_actions = []
