[meta]
id = "studying"
display_name = "Studying"

[soft_constraints]
excludes_actions = [
    "cooking",
]
prefers_locations = []
prefers_poses = []
prefers_expressions = []

[hard_constraints]
excludes_actions = []
requires_props = []
