[meta]
id = "taking_bath"
display_name = "taking bath"

[soft_constraints]
prefers_locations = []
prefers_poses = []
prefers_expressions = []

[hard_constraints]
excludes_actions = []
requires_props = []
